
    public enum KRYaku
    {
        오류 = -1,
        무번화 = 0,
        연칠대 = 1,   // BigFourWinds
        십삼요 = 2,   // BigThreeDragons
        대사희 = 3,   // AllGreen
        대삼원 = 4,   // NineGates
        구련보등 = 5,   // FourKongs
        녹일색 = 6,   // SevenShiftedPairs
        사공 = 7,   // ThirteenOrphans
        사암각 = 8,   // PureTerminalChows
        청요구 = 9,   // LittleFourWinds
        소사희 = 10,  // LittleThreeDragons
        소삼원 = 11,  // AllHonors
        자일색 = 12,  // FourConcealedPungs
        일색쌍룡회 = 13,  // PureKnittedStraight (One-Suit Knitted Straight)
        일색사동순 = 14,  // QuadrupleChow
        일색사절고 = 15,  // FourPureShiftedPungs
        일색사보고 = 16,  // FourPureShiftedChows
        삼공 = 17,  // ThreeKongs
        혼요구 = 18,  // AllTerminalsAndHonors
        칠대 = 19,  // SevenPairs
        칠성불고 = 20,  // GreaterHonorsAndKnittedTiles
        전쌍각 = 21,  // AllEvenPungs
        청일색 = 22,  // FullFlush
        전대 = 23,  // PureTripleChow
        전중 = 24,  // PureShiftedPungs
        전소 = 25,  // UpperTiles only (All 7-9)
        일색삼동순 = 26,  // MiddleTiles only (All 4-6)
        일삭삼절고 = 27,  // LowerTiles only (All 1-3)
        청룡 = 28,  // PureStraight
        삼색쌍룡회 = 29,  // MixedKnittedStraight
        일색삼보고 = 30,  // PureShiftedChows
        전대오 = 31,  // AllFives
        삼동각 = 32,  // TriplePung
        삼암각 = 33,  // ThreeConcealedPungs
        전불고 = 34,  // LesserHonorsAndKnittedTiles
        조합룡 = 35,  // KnittedStraight
        대우오 = 36,  // UpperFour
        소우오 = 37,  // LowerFour
        삼풍각 = 38,  // BigThreeWinds
        묘수회춘 = 39,  // LastTileDraw
        해저로월 = 40,  // LastTileClaim
        공상개화 = 41,  // MixedStraight
        창공화 = 42,  // MixedShiftedPungs
        화룡 = 43,  // NoPointHand
        삼색삼동순 = 44,  // RobbingTheKong
        추부도 = 45,  // OutWithReplacementTile
        삼색삼절고 = 46,  // RobbingTheKong (alternate)
        쌍암공 = 47,  // RobbingTheKong (common name)
        전구인 = 48,  // TwoConcealedKongs
        삼색삼보고 = 49,  // AllPungs
        팽팽화 = 50,  // HalfFlush
        혼일색 = 51,  // MixedTripleChow
        오문제 = 52,  // AllTypes
        쌍전각 = 53,  // TwoDragonsPungs
        불구인 = 54,  // FullyConcealedHand
        화절장 = 55,  // LastTile
        전대요 = 56,  // OutsideHand
        쌍명공 = 57,  // TwoMeldedKongs
        문전청 = 58,  // ConcealedHand
        전각 = 59,  // DragonPung
        권풍각 = 60,  // PrevalentWind
        문풍각 = 61,  // SeatWind
        평화 = 62,  // ClosedWait
        쌍동각 = 63,  // AllChows
        쌍암각 = 64,  // DoublePung
        사귀일 = 65,  // TwoConcealedPungs
        암공 = 66,  // TileHog
        단요 = 67,  // ConcealedKong
        일반고 = 68,  // AllSimples
        희상봉 = 69,  // PureDoubleChow
        연륙 = 70,  // MixedDoubleChow
        노소부 = 71,  // ShortStraight
        요구각 = 72,  // TwoTerminalChows
        결일문 = 73,  // PungOfTerminalsOrHonors
        무자 = 74,  // MeldedKong
        명공 = 75,  // EdgeWait
        변장 = 76,  // SingleWait
        단조장 = 77,  // ClosedWait (alt)
        간장 = 78,  // FlowerPoint (alt)
        자모 = 79,  // SelfDrawn
        화패 = 80,  // FlowerPoint
    }